---
title: "blog"
date: 2018-12-19
---

title: "The exciting journeys of boring people"
author: Patryk
email: patkowalski89@gmail.com

description: >
  I'm glad you are here. I plan to talk about ... Some cool things you can do with your *GitHub* account.
This will be the **first** made-by-me page.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
